#!/usr/bin/env python3
"""
Code Generator - Templates and patterns for code generation
"""

import re
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field


@dataclass
class CodeTemplate:
    """Template for code generation."""
    language: str
    template_type: str  # function, class, module, api, etc.
    name: str
    template: str
    placeholders: Dict[str, str] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    best_practices: List[str] = field(default_factory=list)


class CodeGenerator:
    """Code generation with templates and patterns."""
    
    def __init__(self):
        self.templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, CodeTemplate]:
        """Load code templates."""
        templates = {}
        
        # Python templates
        templates['python_function'] = CodeTemplate(
            language='python',
            template_type='function',
            name='Python Function',
            template='''def {function_name}({parameters}):
    """{description}
    
    Args:
        {arg_docs}
    
    Returns:
        {return_docs}
    
    Raises:
        {exception_docs}
    """
    try:
        # TODO: Implement function logic
        {implementation}
        
        return {return_value}
    except Exception as e:
        # TODO: Handle specific exceptions
        raise RuntimeError(f"Error in {function_name}: {{e}}")''',
            placeholders={
                'function_name': 'function_name',
                'parameters': 'param1, param2=None',
                'description': 'Function description',
                'arg_docs': 'param1: Description, param2: Optional description',
                'return_docs': 'Return value description',
                'exception_docs': 'Exception types and conditions',
                'implementation': '# Function implementation',
                'return_value': 'result'
            },
            dependencies=[],
            best_practices=[
                'Use type hints',
                'Add comprehensive docstring',
                'Include error handling',
                'Add logging for important operations'
            ]
        )
        
        templates['python_class'] = CodeTemplate(
            language='python',
            template_type='class',
            name='Python Class',
            template='''class {class_name}:
    """{description}
    
    Attributes:
        {attribute_docs}
    """
    
    def __init__(self{init_parameters}):
        """Initialize {class_name}.
        
        Args:
            {init_arg_docs}
        """
        {initialization}
    
    def __str__(self):
        """String representation."""
        return f"{class_name}({str_representation})"
    
    def __repr__(self):
        """Official representation."""
        return f"{class_name}({repr_representation})"
    
    {methods}''',
            placeholders={
                'class_name': 'ClassName',
                'description': 'Class description',
                'attribute_docs': 'attr1: Description, attr2: Description',
                'init_parameters': ', param1, param2=None',
                'init_arg_docs': 'param1: Description, param2: Optional description',
                'initialization': 'self.attr1 = param1\n        self.attr2 = param2',
                'str_representation': 'attr1={self.attr1}',
                'repr_representation': 'attr1={self.attr1!r}',
                'methods': '# Add methods here'
            },
            dependencies=[],
            best_practices=[
                'Follow PEP 8 style',
                'Use properties for attribute access',
                'Implement __str__ and __repr__',
                'Add type hints for methods'
            ]
        )
        
        templates['python_api'] = CodeTemplate(
            language='python',
            template_type='api',
            name='Python REST API',
            template='''"""
{api_name} REST API
Generated by Code Skill
"""

from flask import Flask, request, jsonify
from flask_restful import Api, Resource
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
api = Api(app)

class {resource_name}(Resource):
    """{resource_description}"""
    
    def get(self, {get_params}):
        """GET method - retrieve {resource_name}"""
        try:
            {get_implementation}
            return jsonify({get_response})
        except Exception as e:
            logger.error(f"GET error: {{e}}")
            return {{"error": str(e)}}, 500
    
    def post(self):
        """POST method - create {resource_name}"""
        try:
            data = request.get_json()
            {post_implementation}
            return jsonify({post_response}), 201
        except Exception as e:
            logger.error(f"POST error: {{e}}")
            return {{"error": str(e)}}, 500
    
    def put(self, {put_params}):
        """PUT method - update {resource_name}"""
        try:
            data = request.get_json()
            {put_implementation}
            return jsonify({put_response})
        except Exception as e:
            logger.error(f"PUT error: {{e}}")
            return {{"error": str(e)}}, 500
    
    def delete(self, {delete_params}):
        """DELETE method - remove {resource_name}"""
        try:
            {delete_implementation}
            return {{"message": "Deleted successfully"}}, 204
        except Exception as e:
            logger.error(f"DELETE error: {{e}}")
            return {{"error": str(e)}}, 500

# Register routes
api.add_resource({resource_name}, '/{endpoint}', '/{endpoint}/<{param_type}:{param_name}>')

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)''',
            placeholders={
                'api_name': 'API Name',
                'resource_name': 'ResourceName',
                'resource_description': 'Resource description',
                'get_params': 'resource_id',
                'get_implementation': '# Implement GET logic',
                'get_response': '{"data": "example"}',
                'post_implementation': '# Implement POST logic',
                'post_response': '{"id": 1, "created": true}',
                'put_params': 'resource_id',
                'put_implementation': '# Implement PUT logic',
                'put_response': '{"updated": true}',
                'delete_params': 'resource_id',
                'delete_implementation': '# Implement DELETE logic',
                'endpoint': 'resource',
                'param_type': 'int',
                'param_name': 'resource_id'
            },
            dependencies=['flask', 'flask-restful'],
            best_practices=[
                'Add authentication middleware',
                'Implement rate limiting',
                'Add request validation',
                'Include comprehensive error handling',
                'Add API documentation (OpenAPI/Swagger)'
            ]
        )
        
        # JavaScript templates
        templates['javascript_function'] = CodeTemplate(
            language='javascript',
            template_type='function',
            name='JavaScript Function',
            template='''/**
 * {description}
 * 
 * @param {{{param_types}}} {param_names} - {param_descriptions}
 * @returns {{{return_type}}} {return_description}
 * @throws {exception_docs}
 */
function {functionName}({parameters}) {{
    try {{
        // TODO: Implement function logic
        {implementation}
        
        return {returnValue};
    }} catch (error) {{
        // TODO: Handle specific errors
        throw new Error(`Error in ${{functionName}}: ${{error.message}}`);
    }}
}}

// Export if module
{export_statement}''',
            placeholders={
                'description': 'Function description',
                'param_types': 'string, number',
                'param_names': 'param1, param2',
                'param_descriptions': 'Description of parameters',
                'return_type': 'any',
                'return_description': 'Return value description',
                'exception_docs': 'Error conditions',
                'functionName': 'functionName',
                'parameters': 'param1, param2 = null',
                'implementation': '// Function implementation',
                'returnValue': 'result',
                'export_statement': '// module.exports = { functionName };'
            },
            dependencies=[],
            best_practices=[
                'Use JSDoc comments',
                'Add input validation',
                'Include error handling',
                'Follow consistent naming conventions'
            ]
        )
        
        # Add more templates as needed...
        
        return templates
    
    def generate_code(self, language: str, template_type: str, 
                     placeholders: Dict[str, str] = None) -> str:
        """Generate code from template."""
        template_key = f"{language}_{template_type}"
        
        if template_key not in self.templates:
            return f"# No template found for {language} {template_type}"
        
        template = self.templates[template_key]
        
        # Apply placeholders
        code = template.template
        if placeholders:
            for key, value in placeholders.items():
                code = code.replace(f"{{{key}}}", value)
        
        # Fill missing placeholders with defaults
        for key, default in template.placeholders.items():
            if f"{{{key}}}" in code:
                code = code.replace(f"{{{key}}}", default)
        
        return code
    
    def get_available_templates(self, language: str = None) -> List[Dict[str, Any]]:
        """Get available templates."""
        templates = []
        
        for key, template in self.templates.items():
            if language and not key.startswith(language):
                continue
            
            templates.append({
                'key': key,
                'name': template.name,
                'language': template.language,
                'type': template.template_type,
                'description': f"{template.language} {template.template_type} template",
                'placeholders': list(template.placeholders.keys()),
                'dependencies': template.dependencies,
                'best_practices': template.best_practices
            })
        
        return templates
    
    def analyze_code_requirements(self, description: str) -> Dict[str, Any]:
        """Analyze code requirements to suggest templates."""
        description_lower = description.lower()
        
        suggestions = {
            'language': 'python',  # default
            'templates': [],
            'complexity': 'medium',
            'focus_areas': []
        }
        
        # Detect language
        if 'javascript' in description_lower or 'js' in description_lower:
            suggestions['language'] = 'javascript'
        elif 'java' in description_lower:
            suggestions['language'] = 'java'
        elif 'c++' in description_lower or 'cpp' in description_lower:
            suggestions['language'] = 'c++'
        elif 'go' in description_lower or 'golang' in description_lower:
            suggestions['language'] = 'go'
        elif 'rust' in description_lower:
            suggestions['language'] = 'rust'
        
        # Detect template type
        if 'api' in description_lower or 'rest' in description_lower:
            suggestions['templates'].append(f"{suggestions['language']}_api")
            suggestions['complexity'] = 'high'
        
        if 'class' in description_lower:
            suggestions['templates'].append(f"{suggestions['language']}_class")
        
        if 'function' in description_lower or 'method' in description_lower:
            suggestions['templates'].append(f"{suggestions['language']}_function")
        
        # Detect focus areas
        if 'security' in description_lower:
            suggestions['focus_areas'].append('security')
        
        if 'performance' in description_lower or 'fast' in description_lower:
            suggestions['focus_areas'].append('performance')
        
        if 'test' in description_lower:
            suggestions['focus_areas'].append('testing')
        
        # If no specific templates detected, suggest function
        if not suggestions['templates']:
            suggestions['templates'].append(f"{suggestions['language']}_function")
        
        return suggestions


# Example usage
def example():
    """Example of using the code generator."""
    generator = CodeGenerator()
    
    print("Available templates:")
    for template in generator.get_available_templates('python'):
        print(f"  - {template['key']}: {template['name']}")
    
    print("\nGenerating Python function:")
    code = generator.generate_code(
        language='python',
        template_type='function',
        placeholders={
            'function_name': 'calculate_total',
            'description': 'Calculate total price with tax',
            'parameters': 'price, tax_rate=0.08',
            'arg_docs': 'price: Base price, tax_rate: Tax rate (default 0.08)',
            'return_docs': 'Total price including tax',
            'implementation': 'total = price * (1 + tax_rate)\n        return total',
            'return_value': 'total'
        }
    )
    
    print(code)
    
    print("\nAnalyzing requirements:")
    analysis = generator.analyze_code_requirements(
        "Create a REST API for user management with authentication"
    )
    print(analysis)


if __name__ == "__main__":
    example()