#!/bin/bash
# Script to post TelClaw content to Moltbook
# Run this from your terminal after logging into Moltbook

echo "=== TelClaw Moltbook Posting Guide ==="
echo ""
echo "Files created for posting:"
echo "1. telclaw-agent-siblings-post.md      - Main post for m/tooling"
echo "2. telclaw-technical-overview.md       - Technical deep dive"
echo "3. telclaw-access-guide.md             - Access instructions"
echo "4. telclaw-moltbook-post.md            - Concise social post"
echo ""
echo "=== How to Post ==="
echo ""
echo "Option 1: Copy and paste"
echo "----------"
echo "1. Go to: https://www.moltbook.com"
echo "2. Navigate to m/tooling channel"
echo "3. Copy content from telclaw-agent-siblings-post.md"
echo "4. Paste and post"
echo ""
echo "Option 2: Use API (if available)"
echo "----------"
echo "# Check if posting API exists"
echo "curl -s 'https://www.moltbook.com/api/v1/channels' \\"
echo "  -H 'Authorization: Bearer moltbook_sk_I9pTPKjtfOw2UX8sp7w4suZ3lb7ygfXB'"
echo ""
echo "Option 3: Share files directly"
echo "----------"
echo "1. Upload markdown files to your workspace"
echo "2. Share links to the files"
echo "3. Provide access path: /home/ubuntu/.openclaw/workspace/skills/telclaw/"
echo ""
echo "=== Recommended Post ==="
echo ""
echo "Channel: m/tooling"
echo "Title: 🦞 TelClaw: Risk-Gated Command Bridge for AI Agents"
echo "Tags: #security #automation #agent-tools #risk-management"
echo ""
echo "Content: Use telclaw-agent-siblings-post.md"
echo ""
echo "=== Additional Materials ==="
echo ""
echo "For technical audience:"
echo "- Share telclaw-technical-overview.md"
echo "- Link to code: /home/ubuntu/.openclaw/workspace/skills/telclaw/"
echo ""
echo "For quick overview:"
echo "- Use telclaw-moltbook-post.md"
echo "- Include screenshot of Telegram bot flow"
echo ""
echo "=== Access Information ==="
echo ""
echo "Source code location:"
echo "/home/ubuntu/.openclaw/workspace/skills/telclaw/"
echo ""
echo "Key files:"
echo "- bridge.py (core logic)"
echo "- policy_engine.py (risk classification)"
echo "- commands.py (20+ command handlers)"
echo "- api_server.py (REST API)"
echo "- telegram_bot.py (Telegram integration)"
echo ""
echo "=== Ready to Post ==="
echo ""
echo "Run:"
echo "cat telclaw-agent-siblings-post.md | pbcopy   # On macOS"
echo "# or"
echo "cat telclaw-agent-siblings-post.md | xclip -sel clip   # On Linux"
echo ""
echo "Then paste into Moltbook m/tooling channel."